import { GoogleGenAI } from '@google/genai';
import fs from 'fs';
import path from 'path';

function readComponentFiles(dirPath) {
  let combinedContent = '';
  try {
    if (fs.existsSync(dirPath)) {
      function scan(currentPath) {
        const items = fs.readdirSync(currentPath);
        for (const item of items) {
          const fullPath = path.join(currentPath, item);
          const stat = fs.statSync(fullPath);
          if (stat.isDirectory()) {
            scan(fullPath);
          } else if (item.endsWith('.tsx') || item.endsWith('.jsx') || item.endsWith('.ts') || item.endsWith('.js')) {
            const fileData = fs.readFileSync(fullPath, 'utf8');
            combinedContent += `\n--- FILE: ${item} ---\n${fileData}\n`;
          }
        }
      }
      scan(dirPath);
    }
  } catch (error) {
    console.error("Error running directory scanner:", error);
  }
  return combinedContent;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { message } = req.body || {};
    if (!message) return res.status(400).json({ error: "Message is required" });

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ success: false, error: "GEMINI_API_KEY environment variable is missing." });
    }

    const componentsPath = path.join(process.cwd(), 'src', 'components');
    const frontendCodebase = readComponentFiles(componentsPath);

    const systemInstruction = `
      You are the official AI chat persona for this gymnastics athlete website.
      Your personality is energetic, friendly, cute, and uses casual slang/emojis.
      
      You must answer user questions based on the text, content, schedules, prices, or links found directly inside the frontend code files provided below. Ignore the code syntax/imports and focus entirely on the hardcoded text data, strings, and components.
      
      FRONTEND CODE CONTEXT:
      ${frontendCodebase || "No frontend components found."}
    `;

    const ai = new GoogleGenAI({ apiKey });

    // Use official SDK generateContent call
    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: message,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.7,
      }
    });

    const replyText = response.text || response.candidates?.[0]?.content?.parts?.[0]?.text;

    if (replyText) {
      return res.status(200).json({
        success: true,
        reply: replyText
      });
    } else {
      throw new Error("No response generated by Gemini model.");
    }
  } catch (error) {
    console.error("Gemini Error:", error);
    return res.status(500).json({
      success: false,
      error: "The AI engine pipeline crashed",
      details: error.message
    });
  }
}
